version: '3'

services:
  service_cep:
    build: ./service_cep
    restart: always
    ports:
      - "8080:8080"

  service_weather:
    build: ./service_weather
    restart: always

  collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml

  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"
